services:
  rocketwatch:
    image: haloooloolo/rocketwatch
    build:
      context: .
      dockerfile: rocketwatch/Dockerfile
    volumes:
      - ./rocketwatch/contracts/rocketpool:/app/rocketwatch/contracts/rocketpool
      - ./rocketwatch/config.toml:/app/rocketwatch/config.toml
      - ./transcriptions:/app/transcriptions
    restart: unless-stopped
    depends_on:
      - mongodb
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    labels:
      com.centurylinklabs.watchtower.enable: true

  mongodb:
    image: mongo:8.2.6
    volumes:
      - ./mongodb:/data/db
    restart: unless-stopped
    command: --setParameter diagnosticDataCollectionEnabled=false
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    ports:
      - "127.0.0.1:27017:27017"

  watchtower:
    image: nickfedor/watchtower:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    command: --interval 30
      --label-enable
